[profile.default]
src = "src"
out = "out"
libs = ["lib"]
allow_paths = ["../../../contracts/src"]

dynamic_test_linking = true

optimizer = true
optimizer_runs = 200
solc_version = "0.8.23"


[fmt]
single_line_statement_blocks = "multi"
multiline_func_header = "params_first_multi"
override_spacing = false


[lint]
mixed_case_exceptions = [
    "ERC",
    "URI",
    "ID",
    "UUID",
]
ignore = [
  "*.t.sol"
]
